### ISSUE TITLE
PromPush thread sometimes dies

### ISSUE THREAD

**Issue by rspier** [sulrich/weewx-prompush#3]
Short version:
  Sometimes the PromPush thread silently dies.
  There's nothing (useful) in the log such as an error.

I don't see anything obvious in the prompush code that would cause this.  Next time it happens, I'll try and collect more data.

**Comment by sulrich** [comment]
my apologies, i ran into this sometimes when i was using this periodically.  i should have put a note here. 

i noticed that it would happen when there was an issue with the push-gw or it was unavailable.  i never really took the time to dig into this and i no longer have the setup to troubleshoot this myself.

**Comment by tomdotorg** [comment]
I'm having the same thing. I just get started with this extension and it is a great. When the prom-push component goes offline for one reason or another, the thread dies - every time. I will look into it though I am not experienced with Python nor weewx extensions. What could go wrong?

**Comment by tomdotorg** [comment]
Got a look at this. It looks like a connection refused error forces the thread to shut down. Am going to try wrapping the requests call to handle exceptions. Will report back.

**Comment by rspier** [comment]
@tomdotorg Did you have any luck with the exception handling?

**Comment by tomdotorg** [comment]
Yes, I wound up forking the repo to handle the exception, but also to rename the metrics in a more Prometheus style.

https://github.com/tomdotorg/weewx-prometheus

**Comment by rspier** [comment]
Cool, thanks.  I'm not sure I'm a fan of that new style of metrics, there's a ton of redundant information in the variable names which (imho) is already covered by the job label.  I also don't want to lose my weather history, so I'll backport the change here.
